#include "pseudopurefluids/Air.cpp"
#include "pseudopurefluids/R507A.cpp"
#include "pseudopurefluids/R407C.cpp"
#include "pseudopurefluids/R410A.cpp"
#include "pseudopurefluids/R404A.cpp"
#include "pseudopurefluids/SES36.cpp"

#include "purefluids/Argon.cpp"
#include "purefluids/Alkanes.cpp"
#include "purefluids/Benzene.cpp"
#include "purefluids/Butenes.cpp"
#include "purefluids/Cyclopentane.cpp"
#include "purefluids/Cyclopropane_Propyne.cpp"
#include "purefluids/Deuterium.cpp"
#include "purefluids/DMC.cpp"
#include "purefluids/Ethanol.cpp"
#include "purefluids/Ether.cpp"
#include "purefluids/Ethylene.cpp"
#include "purefluids/FAME.cpp"
#include "purefluids/Fluorine.cpp"
#include "purefluids/Helium.cpp"
#include "purefluids/HFE143m.cpp"
#include "purefluids/Hydrogen.cpp"
#include "purefluids/IndustrialFluids.cpp"
#include "purefluids/Methanol.cpp"
#include "purefluids/Neon.cpp"
#include "purefluids/Nitrogen.cpp"
#include "purefluids/Oxygen.cpp"
#include "purefluids/Propylene.cpp"
#include "purefluids/R12_R113.cpp"
#include "purefluids/R124.cpp"
#include "purefluids/R125.cpp"
#include "purefluids/R1234yf.cpp"
#include "purefluids/R1234ze.cpp"
#include "purefluids/R134a.cpp"
#include "purefluids/R143A.cpp"
#include "purefluids/R161.cpp"
#include "purefluids/R22.cpp"
#include "purefluids/R227EA_R365MFC.cpp"
#include "purefluids/R23.cpp"
#include "purefluids/R236FA.cpp"
#include "purefluids/R236EA.cpp"
#include "purefluids/R290.cpp"
#include "purefluids/R32.cpp"
#include "purefluids/R717.cpp"
#include "purefluids/R744.cpp"
#include "purefluids/RC318_R21_R114_R13_R14.cpp"
#include "purefluids/Siloxanes.cpp"
#include "purefluids/Span_Short.cpp"
#include "purefluids/SulfurHexafluoride.cpp"
#include "purefluids/Undecane.cpp"
#include "purefluids/Water.cpp"
#include "purefluids/Xylene_EthylBenzene.cpp"





