#This file is automatically generated by the generate_constants_module.py script in dev/scripts.
#DO NOT MODIFY THE CONTENTS OF THIS FILE!
cimport param_constants_header

iB = param_constants_header.iB
iT = param_constants_header.iT
iP = param_constants_header.iP
iD = param_constants_header.iD
iC = param_constants_header.iC
iC0 = param_constants_header.iC0
iO = param_constants_header.iO
iU = param_constants_header.iU
iH = param_constants_header.iH
iS = param_constants_header.iS
iA = param_constants_header.iA
iG = param_constants_header.iG
iQ = param_constants_header.iQ
iV = param_constants_header.iV
iL = param_constants_header.iL
iI = param_constants_header.iI
iMM = param_constants_header.iMM
iTcrit = param_constants_header.iTcrit
iTtriple = param_constants_header.iTtriple
iPtriple = param_constants_header.iPtriple
iPcrit = param_constants_header.iPcrit
iRhocrit = param_constants_header.iRhocrit
iAccentric = param_constants_header.iAccentric
iDpdT = param_constants_header.iDpdT
iDrhodT_p = param_constants_header.iDrhodT_p
iTmin = param_constants_header.iTmin
iDipole = param_constants_header.iDipole
