cdef extern from "CoolProp.h":
    enum params:
        iT
        iP
        iD
        iQ
        iH
        iS
        iB
        iC
        iC0
        iO
        iU
        iA
        iG
        iQ
        iV
        iL
        iI
        iMM
        iTcrit
        iTtriple
        iPcrit
        iRhocrit
        iAccentric
        iDpdT
        iDrhodT_p
        iTmin
        iDipole