for file in ['mixture_excess_term.json']:
    json = open(file,'r').read()
    
    # Escape all existing quotations
    json = json.replace('"','\\"')
    
    # Split into lines
    json = json.split('\n')
    
    # Add " to beginning and end of every line
    for i,line in enumerate(json):
        json[i] = '"'+line+'"'
    
    # Back together
    json = '\n'.join(json)
    
    # Header/footer
    json = '// File generated by the script dev/mixtures/JSON_to_C++.py\n\nconst char mixture_excess_JSON[] = ""\n' + json + ';'
    
    f = open('../../CoolProp/mixture_excess_JSON.h','w')
    
    print>>f, json