#This file is automatically generated by the generate_constants_module.py script in dev/scripts.
#DO NOT MODIFY THE CONTENTS OF THIS FILE!

cdef extern from "CoolProp.h":
	enum params:
		iB
		iT
		iP
		iD
		iC
		iC0
		iO
		iU
		iH
		iS
		iA
		iG
		iQ
		iV
		iL
		iI
		iMM
		iTcrit
		iTtriple
		iPtriple
		iPcrit
		iRhocrit
		iAccentric
		iDpdT
		iDrhodT_p
		iTmin
		iDipole
