#This file is automatically generated by the generate_constants_module.py script in dev/scripts.
#DO NOT MODIFY THE CONTENTS OF THIS FILE!
cimport param_constants_header

iB = param_constants_header.iB
iT = param_constants_header.iT
iP = param_constants_header.iP
iD = param_constants_header.iD
iC = param_constants_header.iC
iC0 = param_constants_header.iC0
iO = param_constants_header.iO
iU = param_constants_header.iU
iH = param_constants_header.iH
iS = param_constants_header.iS
iA = param_constants_header.iA
iG = param_constants_header.iG
iQ = param_constants_header.iQ
iV = param_constants_header.iV
iL = param_constants_header.iL
iI = param_constants_header.iI
iMM = param_constants_header.iMM
iTcrit = param_constants_header.iTcrit
iTtriple = param_constants_header.iTtriple
iTreduce = param_constants_header.iTreduce
iPtriple = param_constants_header.iPtriple
iPcrit = param_constants_header.iPcrit
iRhocrit = param_constants_header.iRhocrit
iRhoreduce = param_constants_header.iRhoreduce
iAccentric = param_constants_header.iAccentric
iDpdT = param_constants_header.iDpdT
iDrhodT_p = param_constants_header.iDrhodT_p
iTmin = param_constants_header.iTmin
iDipole = param_constants_header.iDipole
iPhase = param_constants_header.iPhase
iPHASE_LIQUID = param_constants_header.iPHASE_LIQUID
iPHASE_GAS = param_constants_header.iPHASE_GAS
iPHASE_SUPERCRITICAL = param_constants_header.iPHASE_SUPERCRITICAL
iPHASE_TWOPHASE = param_constants_header.iPHASE_TWOPHASE
iODP = param_constants_header.iODP
iGWP20 = param_constants_header.iGWP20
iGWP100 = param_constants_header.iGWP100
iGWP500 = param_constants_header.iGWP500
iCritSplineT = param_constants_header.iCritSplineT
iHcrit = param_constants_header.iHcrit
iScrit = param_constants_header.iScrit
